# fly.toml app configuration file generated for blog-list-app-backend on 2023-12-27T21:56:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-list-app-backend"
primary_region = "otp"

[build]
  command = "npm install"

[env]
  PORT = "3003"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
